### ISSUE TITLE
Unknown plugin "transform-decorators-legacy" 

### ISSUE THREAD

**Issue by codeuniquely** [glortho/react-keydown#78]
Getting this error trying to use the decorator

Building with 
* "react": "^16.2.0",
* "babel": "^6.23.0",
* "babel-preset-es2015": "^6.18.0",
* "babel-preset-react": "^6.16.0",
* "babel-preset-stage-0": "^6.24.1",

```
ERROR in ./node_modules/react-keydown/es/index.js
Module build failed: ReferenceError: Unknown plugin "transform-decorators-legacy" specified in "/project/node_modules/react-keydown/.babelrc" at 0, attempted to resolve relative to "/project/node_modules/react-keydown"
    at /project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/project/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/project/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/project/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/project/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/project/node_modules/babel-loader/lib/index.js:163:20)
 @ multi core-js react react-dom prop-types react-router react-router-dom react-keydown intl react-intl
```

Do I need to add babel presets to my projects '.babelrc' file  ???

**Comment by glortho** [comment]
@codeuniquely it sounds like you're not ignoring node_modules in your own transpilation/bundle settings. is that true? react-keydown is already transpiled so you should ignore it
